name: tests-auth
on: 
  pull_request:
    paths: 
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  #take all our code out of the project
      - run: cd auth && npm install && npm run test:ci
