name: tests-tickets
on: 
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  #take all our code out of the project
      - run: cd payments && npm install && npm run test:ci
