name: tests-tickets
on: 
  pull_request:
    paths: 
      - 'tickets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  #take all our code out of the project
      - run: cd tickets && npm install && npm run test:ci
